public enum AirportCode {
    JFK, LAX, ORD, ATL, SFO, DFW, DEN, SEA, MIA, LAS,
    IAH, PHX, MSP, DTW, BOS, EWR, CLT, MCO, PHL, LGA,
    IAD, DCA, MDW, BWI, HNL, SAN, BNA, STL, TPA, PDX,
    DAL, MCI, FLL, MSY, RDU, SJU, SLC, AUS, OAK, SMF,
    PIT, CLE, IND, CMH, SNA, SAT, JAX, ANC, ABQ,
    BUR, BDL, BUF, CUN, CVG, DAY, DSM, DUB, GDL,
    GRR, GSO, GSP, HOU, ICT, JNB, KOA, LBB, LIT, LGB,
    MEM, MHT, MRY, OKC, OMA, ONT, PBI, PWM, RIC, ROC,
    SDF, SJC, SJT, SRQ, SYR, TUS, TYS, VPS, YEG,
    YHZ, YOW, YQB, YUL, YVR, YYC, YYZ, AMS, CDG, DXB,
    FRA, HKG, ICN, LHR, NRT, PEK, SIN, ZRH
}
